import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, ScrollView, Share, TextInput, View, useWindowDimensions } from 'react-native';
import { Text } from 'heroui-native';
import { loadLeaderboard, loadPlayerName, submitGlobalScore, type GlobalScore } from '@/lib/game/leaderboard';
import type { HighScore } from '@/lib/game/types';

interface GameOverOverlayProps { score: number; coins: number; highScores: HighScore[]; onRetry: () => void; onMenu: () => void; }
const PLAY_STORE_URL = 'https://play.google.com/store/apps/details?id=com.harshamin.piratesplunder';
const INK='#25160c', PARCHMENT='#e7c57f', LIGHT='#f4deb0', WOOD='#2d1a10', GOLD='#e5aa2d', RED='#9f1117';

export function GameOverOverlay({ score, coins, onRetry }: GameOverOverlayProps) {
  const { height } = useWindowDimensions(); const compact = height < 760;
  const [name,setName]=useState(''); const [globalScores,setGlobalScores]=useState<GlobalScore[]>([]); const [submitting,setSubmitting]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{ void loadPlayerName().then(setName); void loadLeaderboard().then(r=>setGlobalScores(r.leaderboard),()=>setError('Leaderboard is temporarily unavailable.')); },[]);
  const leaderboard=useMemo(()=>[...globalScores].sort((a,b)=>b.score-a.score).slice(0,10),[globalScores]);
  const projectedRank=useMemo(()=>leaderboard.filter(e=>e.score>score).length+1,[leaderboard,score]); const isTopTen=leaderboard.length<10||projectedRank<=10;
  const submit=async()=>{const clean=name.trim(); if(!clean||submitting||submitted)return; setSubmitting(true);setError('');try{const r=await submitGlobalScore(clean,score,coins);setGlobalScores(r.leaderboard);setSubmitted(true);}catch{setError('Could not submit your score. Please try again.');}finally{setSubmitting(false);}};
  const shareScore=async()=>{const message=`🏴‍☠️ I scored ${score.toLocaleString()} in Pirate's Plunder! Think you can beat my score?\n\n${PLAY_STORE_URL}`;try{if(Platform.OS==='web'){const nav=globalThis.navigator as (Navigator&{share?:(d:{title?:string;text?:string;url?:string})=>Promise<void>})|undefined;if(nav?.share)await nav.share({title:"Pirate's Plunder",text:`🏴‍☠️ I scored ${score.toLocaleString()} in Pirate's Plunder! Think you can beat my score?`,url:PLAY_STORE_URL});return;}await Share.share({title:"Pirate's Plunder",message});}catch{}};
  const rowH=compact?27:30;
  return <View style={{position:'absolute',inset:0,backgroundColor:'#06465c'}}>
    <View style={{position:'absolute',top:0,left:'10%',right:'10%',height:150,backgroundColor:'rgba(44,194,218,.18)',borderBottomLeftRadius:180,borderBottomRightRadius:180}}/><Text style={{position:'absolute',left:4,bottom:25,fontSize:60}}>🪙</Text><Text style={{position:'absolute',right:6,bottom:35,fontSize:68,opacity:.6}}>⚓</Text>
    <ScrollView bounces={false} showsVerticalScrollIndicator={false} contentContainerStyle={{flexGrow:1,alignItems:'center',justifyContent:'center',paddingHorizontal:12,paddingTop:compact?8:14,paddingBottom:compact?10:18}}>
      <View style={{width:'100%',maxWidth:430,alignItems:'center'}}>
        <Pressable onPress={()=>void shareScore()} style={({pressed})=>({position:'absolute',right:0,top:5,zIndex:20,width:58,height:58,borderRadius:7,borderWidth:3,borderColor:GOLD,backgroundColor:pressed?'#3a2112':'#2a190f',alignItems:'center',justifyContent:'center'})}><Text maxFontSizeMultiplier={1} style={{color:'#ffe09a',fontSize:23,lineHeight:24}}>⇧</Text><Text maxFontSizeMultiplier={1} style={{color:'#ffe09a',fontSize:9,fontWeight:'900'}}>SHARE</Text></Pressable>
        <Text maxFontSizeMultiplier={1} style={{fontSize:compact?49:58,lineHeight:compact?53:62,zIndex:4,marginBottom:-10}}>☠️</Text>
        <View style={{width:'86%',backgroundColor:WOOD,borderWidth:4,borderColor:'#6f401c',borderRadius:9,alignItems:'center',paddingVertical:compact?5:7,zIndex:3,shadowColor:'#000',shadowOpacity:.45,shadowRadius:8,elevation:8}}><Text maxFontSizeMultiplier={1} style={{color:'#f0b52f',fontSize:compact?43:50,lineHeight:compact?46:53,fontWeight:'900',letterSpacing:1.5,textShadowColor:'#100905',textShadowRadius:2}}>SUNK!</Text><Text maxFontSizeMultiplier={1} style={{color:'#f7dfad',fontSize:9,fontWeight:'900'}}>YOUR TREASURE SANK TO THE DEPTHS!</Text></View>
        <View style={{width:'92%',marginTop:-3,paddingHorizontal:compact?15:18,paddingTop:compact?12:15,paddingBottom:compact?11:14,backgroundColor:PARCHMENT,borderWidth:3,borderColor:'#9a6a2c',borderRadius:13,shadowColor:'#000',shadowOpacity:.35,shadowRadius:10,elevation:7}}>
          <Text maxFontSizeMultiplier={1} style={{color:INK,textAlign:'center',fontSize:compact?18:21,fontWeight:'900'}}>──  YOUR SCORE  ──</Text>
          <View style={{alignSelf:'center',width:'72%',backgroundColor:WOOD,borderRadius:5,borderWidth:2,borderColor:'#170d08',marginTop:5,paddingVertical:compact?3:5}}><Text maxFontSizeMultiplier={1} style={{color:'#ffd958',textAlign:'center',fontSize:compact?29:34,lineHeight:compact?32:37,fontWeight:'900'}}>{score.toLocaleString()}</Text></View>
          <View style={{flexDirection:'row',marginTop:compact?8:10,gap:7}}><TextInput value={name} onChangeText={setName} maxLength={20} editable={!submitted} autoCapitalize="words" returnKeyType="done" onSubmitEditing={()=>void submit()} placeholder="Enter your name..." placeholderTextColor="#7c684e" style={{flex:1,minWidth:0,height:compact?38:42,borderRadius:7,borderWidth:2,borderColor:'#80603d',backgroundColor:LIGHT,paddingHorizontal:10,color:INK,fontSize:14}}/><Pressable disabled={!name.trim()||submitting||submitted} onPress={()=>void submit()} style={({pressed})=>({width:compact?92:100,height:compact?38:42,borderRadius:6,borderWidth:3,borderColor:'#6c2a13',backgroundColor:submitted||!name.trim()?'#8e704f':pressed?'#771016':RED,alignItems:'center',justifyContent:'center'})}><Text maxFontSizeMultiplier={1} style={{color:'#ffe8ad',fontSize:13,fontWeight:'900'}}>{submitted?'SAVED':'SUBMIT'}</Text></Pressable></View>
          <Text maxFontSizeMultiplier={1} style={{color:'#5e452b',textAlign:'center',fontSize:10,marginTop:3}}>Submit your score to the leaderboard!</Text>{submitting?<ActivityIndicator color={RED} style={{marginTop:3}}/>:null}{error?<Text style={{color:'#8b1e1e',textAlign:'center',fontSize:9,marginTop:2}}>{error}</Text>:null}
          <Text maxFontSizeMultiplier={1} style={{color:INK,textAlign:'center',fontSize:compact?19:22,fontWeight:'900',marginTop:compact?7:9,marginBottom:3}}>☠  LEADERBOARD</Text>
          <View style={{borderTopWidth:1,borderTopColor:'#9d7746'}}>{leaderboard.map((e,i)=>{const current=submitted&&e.name===name.trim()&&e.score===score;const medal=i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}`;return <View key={`${e.createdAt}-${i}`} style={{height:rowH,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:'rgba(111,78,40,.22)',paddingHorizontal:5,backgroundColor:current?'#49321f':'transparent',borderRadius:current?4:0}}><Text maxFontSizeMultiplier={1} style={{width:45,color:current?'#fff1c5':INK,fontSize:i<3?18:13,fontWeight:'900',textAlign:'center'}}>{medal}</Text><Text numberOfLines={1} maxFontSizeMultiplier={1} style={{flex:1,color:current?'#fff1c5':INK,fontSize:compact?12:13,fontWeight:current?'900':'700'}}>{current?'You':e.name}</Text><Text style={{color:'#d99a11',fontSize:14,marginRight:5}}>●</Text><Text maxFontSizeMultiplier={1} style={{width:68,textAlign:'right',color:current?'#fff1c5':INK,fontSize:compact?12:13,fontWeight:'800'}}>{e.score.toLocaleString()}</Text></View>})}{leaderboard.length===0&&!error?<Text style={{color:'#6a4a27',textAlign:'center',paddingVertical:12,fontSize:11}}>Be the first captain on the leaderboard!</Text>:null}</View>
        </View>
        <View style={{width:'82%',marginTop:-1,backgroundColor:'#21170f',borderBottomLeftRadius:12,borderBottomRightRadius:12,alignItems:'center',paddingVertical:compact?7:9,paddingHorizontal:10}}><Text maxFontSizeMultiplier={1} style={{color:'#fff0c0',fontSize:compact?14:16,fontWeight:'900'}}>YOUR SCORE: <Text style={{color:'#ffd95a'}}>{score.toLocaleString()}</Text></Text><Text maxFontSizeMultiplier={1} style={{color:'#ead7ac',fontSize:compact?9:10,marginTop:1,textAlign:'center'}}>{isTopTen?`Currently good for #${projectedRank} on the leaderboard.`:'Not in the top 10 yet, but keep playing!'}</Text></View>
        <Pressable onPress={onRetry} style={({pressed})=>({width:'76%',height:compact?49:56,marginTop:compact?8:11,borderWidth:4,borderColor:GOLD,backgroundColor:pressed?'#761017':RED,borderRadius:9,alignItems:'center',justifyContent:'center',shadowColor:'#000',shadowOpacity:.5,shadowRadius:7,elevation:8})}><Text maxFontSizeMultiplier={1} style={{color:'#ffe5a0',fontSize:compact?20:23,fontWeight:'900'}}>⚔  PLAY AGAIN</Text></Pressable>
      </View>
    </ScrollView>
  </View>;
}
